# Generated by Django 4.2.6 on 2023-10-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_createques_delete_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateQues',
        ),
    ]
